### ISSUE TITLE
timezone defaults to UTC in docker

### ISSUE THREAD

**Issue by alekspickle** [Yuri6037/time-tz#17]
So if you build in docker `get_timezone` will return `Etc/UTC` by default and would be wrong.

For example I am in berlin tz and some of the machines I tried it are in other tz's. It always returns UTC, which is weird.

MRE:
```
    let tz = time_tz::system::get_timezone().unwrap_or_else(|_| timezones::db::europe::BERLIN);

```

if you create a simple binary and wrap it in docker this will not fail, but instead return `UTC`.

**Comment by Yuri6037** [comment]
`time_tz::system::get_timezone()` uses `/etc/localtime` can you check to what file this `/etc/localtime` points to?

Note: if all you're after is to get the current system time in local time and not the actual timezone, you can check out `bp3d-os` with the `time` feature.

**Comment by alekspickle** [comment]
Fair enough, but still it kinda unexpected.
The content of all images I checked:

```
root@0e903dfdb4c9:/app# cat /etc/localtime
TZif2UTCTZif2UTC
UTC0
```

**Comment by Yuri6037** [comment]
> Fair enough, but still it kinda unexpected. The content of all images I checked:
> 
> ```
> root@0e903dfdb4c9:/app# cat /etc/localtime
> TZif2UTCTZif2UTC
> UTC0
> ```

Unfortunately, given this output there's not much I can do. Maybe you could use the built-in TZ environment variable parser and use the TZ parser if there is a TZ variable.

**Comment by alekspickle** [comment]
It's unfortunate: it basically means this crate is unusable in docker.
